### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0 when attempting to use an inline PowerShellScriptsElevatedDeferred

### ISSUE THREAD

**Issue by jzajac2** [flcdrg/PowerShellWixExtension#7]
I am trying to use an embedded powershell script, which for now is just using your example code to take my own code of of the picture:

```
<powershell:Script Id="ps1New_SendConnector" Elevated="yes">
      <![CDATA[ 

        $wid=[System.Security.Principal.WindowsIdentity]::GetCurrent()
        $prp=new-object System.Security.Principal.WindowsPrincipal($wid)
        $adm=[System.Security.Principal.WindowsBuiltInRole]::Administrator
    
        Write-Host $wid.Name
        Write-Host $prp.IsInRole($adm)

        for ($i = 1; $i -le 100; $i += 10) 
        { 
          Write-Progress -Activity "Activity" -Status "Status $i% complete" -CurrentOperation "Operation $i" -PercentComplete $i
          Start-Sleep -Milliseconds 5 
        }

    ]]>
    </powershell:Script>
```

I get an error however:

```
MSI (s) (78:EC) [13:43:52:945]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIF5FD.tmp, Entrypoint: PowerShellScriptsElevatedDeferred
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIF5FD.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action PowerShellActions!PowerShellActions.CustomActions.PowerShellScriptsElevatedDeferred
Executing PowerShell script:
 

        $wid=::GetCurrent()
        $prp=new-object System.Security.Principal.WindowsPrincipal($wid)
        $adm=::Administrator
    
        Write-Host $wid.Name
        Write-Host $prp.IsInRole($adm)

        for ($i = 1; $i -le 100; $i += 10) 
        { 
          Write-Progress -Activity "Activity" -Status "Status $i% complete" -CurrentOperation "Operation $i" -PercentComplete $i
          Start-Sleep -Milliseconds 5 
        }

    
PowerShell terminating error, returning Failure
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at PowerShellActions.PowerShellTask..ctor(String script, Session session)
   at PowerShellActions.CustomActions.ScriptsDeferred(Session session, String deferredProperty)
```

I haven't fully educated myself on how these WiX Extensions work, so sorry in advance. Is my own WiX installer project responsible for getting this System.Management.Automation dependency on the system in a way that your PowerShellActions code can bind to it?

For the full picture, here is the fusion log:

```
*** Assembly Binder Log Entry  (5/16/2016 @ 1:35:48 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Windows\SysWOW64\rundll32.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Windows/Installer/MSI8F52.tmp-
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : PowerShellActions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Windows\Installer\MSI8F52.tmp-\CustomAction.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/Installer/MSI8F52.tmp-/System.Management.Automation.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Installer/MSI8F52.tmp-/System.Management.Automation/System.Management.Automation.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Installer/MSI8F52.tmp-/System.Management.Automation.EXE.
LOG: Attempting download of new URL file:///C:/Windows/Installer/MSI8F52.tmp-/System.Management.Automation/System.Management.Automation.EXE.
LOG: All probing URLs attempted and failed.

```

**Comment by flcdrg** [comment]
This will happen if the version(s) of PowerShell you have installed on your computer don't supply the System.Management.Automation, Version=3.0.0.0 assembly.

What version of Windows are you using and what version of PowerShell do you have installed?

**Comment by flcdrg** [comment]
FYI have a look at the updated code in https://github.com/flcdrg/PowerShellWixExtension/blob/master/Tests/PowerShellWixInlineScriptTest/Product.wxs - you need to 'escape' the square brackets in the script to get the script to run correctly

**Comment by jzajac2** [comment]
I need this to work on Windows Server 2008 R2 Standard (SP1). my env currently has v1.0 of powershell.  I'm going to apply updates and it may come to at least 2.0 (unless the Windows Update doesn't cover Windows Management Framework at all). 

Does your custom action code truly require v3 support? For example, if I wanted to support v1.0, would I be able to just build your custom action project with the System.Management.Automation v1.0? Or do you have code or any other reason which would make this a bad idea?

**Comment by flcdrg** [comment]
So I'm pretty sure it doesn't technically require v3 (I think when i first started it did use v1), but when compiling you need to pick an assembly to reference, and more recent operating systems don't include the old v1 assembly. eg. Looking at my Windows 10 box, I only have the v3 ones installed.

So in your case, unless you upgrade to at least PowerShell v3, then you'll have to do your own private build against v1. (There is no 'v2' reference assembly - just v1 and now v3)

**Comment by flcdrg** [comment]
Raised #11 which would cover this
